### ISSUE TITLE
An api request

### ISSUE THREAD

**Issue by EthanChinCN** [maliMirkec/code-line-daily#3]
Can I expect an api for this amazing project?  I'm interested in build an iOS calendar app for this project

**Comment by maliMirkec** [comment]
Hi, you could expect an API in the following weeks. Do you have any specific requirements? I am open to suggestions.

**Comment by EthanChinCN** [comment]
> Hi, you could expect an API in the following weeks. Do you have any specific requirements? I am open to suggestions.

I'm glad to hear that. I have no experience in api development, but a little suggestion would be that add time zone or local parameters, so it shows accurate time in different time zone.

**Comment by maliMirkec** [comment]
@EthanChinCN API is completed. See README for more info.

**Comment by maliMirkec** [comment]
Resolved.
